name: BAD spongeurl

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: BAD
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: unit tests
        run: mvn -B test --file pom.xml

      - name: build the app
        run: |
          mvn clean 
          mvn -B package --file pom.xml
